### ISSUE TITLE
Command parser should merge user/channel mentions into a single argument

### ISSUE THREAD

**Issue by Reapimus** [shayypy/guilded.py#49]
Currently, I have to explain to users that they need to surround a user or channel mention in quotation marks purely due to the fact that the library's command parser recognizes user/channel mentions with multiple words separated by spaces as individual arguments instead of a single argument. It would be much better if the command parser could recognize user/channel mentions toward users & channels in the bot's cache and merge them into one argument.

**Comment by shayypy** [comment]
This is not (reasonably) possible currently due to Guilded limitations. The raw data you receive from Guilded is the name of the mentioned object, including spaces. Ideally, mentions should have their own machine-readable format within Guilded's markdown superset. They are hardly useful as mentions otherwise.
